spring.application.name=hostel_management
spring.datasource.url=jdbc:mysql://localhost:3306/hostel_management
spring.datasource.username=root
spring.datasource.password=axway123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=9090
# jwt properties
jwt.secret=secret
SECRET_KEY="YourSuperSecretKeyForJwtAuthenticationExample"
jwt.expirationMs=86400000

